/**
 * Created by ljunb on 16/5/25.
 * action类型
 */

// 搜索actions
export const FETCH_KEYWORDS_LIST = 'FETCH_KEYWORDS_LIST';
export const RECEIVE_KEYWORDS_LIST = 'RECEIVE_KEYWORDS_LIST';
export const SELECT_KEYWORD = 'SELECT_KEYWORD';
export const RESET_SEARCH_STATE = 'RESET_SEARCH_STATE';
export const CACHE_HISTORY = 'CACHE_HISTORY';
export const CLEAR_HISTORY = 'CLEAR_HISTORY';
export const SETUP_SEARCH_TEXT = 'SETUP_SEARCH_TEXT';
export const FETCH_SEARCH_RESULT_LIST = 'FETCH_SEARCH_RESULT_LIST';
export const RECEIVE_SEARCH_RESULT_LIST = 'RECEIVE_SEARCH_RESULT_LIST';
export const CHANGE_SORT_VIEW_STATUS_SEARCH = 'CHANGE_SORT_VIEW_STATUS_SEARCH';
export const SELECT_SORT_TYPE_SEARCH = 'SELECT_SORT_TYPE_SEARCH';
export const FETCH_SORT_TYPES_LIST_SEARCH = 'FETCH_SORT_TYPES_LIST_SEARCH';
export const RECEIVE_SORT_TYPES_LIST_SEARCH = 'RECEIVE_SORT_TYPES_LIST_SEARCH';
export const ORDER_ASC_OR_DESC_SEARCH = 'ORDER_ASC_OR_DESC_SEARCH';
export const CHANGE_HEALTH_LIGHT_SEARCH = 'CHANGE_HEALTH_LIGHT_SEARCH';
export const SELECT_FOOD_TAG = 'SELECT_FOOD_TAG';

// 食物对比actions
export const SELECT_COMPARE_FOOD = 'SELECT_COMPARE_FOOD';
export const CLEAR_COMPARE_FOOD = 'CLEAR_COMPARE_FOOD';
export const FETCH_FOOD_BRIEF = 'FETCH_FOOD_BRIEF';
export const RECEIVE_FOOD_BRIEF = 'RECEIVE_FOOD_BRIEF';
export const FOOD_COMPARE_RESET_STATE = 'FOOD_COMPARE_RESET_STATE';

// 食物详情actions
export const FOOD_INFO_FETCH_FOOD = 'FOOD_INFO_FETCH_FOOD';
export const FOOD_INFO_RECEIVE_FOOD = 'FOOD_INFO_RECEIVE_FOOD';
export const FOOD_INFO_CHANGE_SHOW_UNITS_STATUS = 'FOOD_INFO_CHANGE_SHOW_UNITS_STATUS';

// 逛吃actions
export const FEED_HOME_LIST_FETCH_LIST = 'FEED_HOME_LIST_FETCH_LIST';
export const FEED_HOME_LIST_RECEIVE_LIST = 'FEED_HOME_LIST_RECEIVE_LIST';