/**
 * Created by ljunb on 16/5/25.
 * action类型
 */
// 轮播action
export const FETCH_BANNER_LIST = 'FETCH_BANNER_LIST';
export const RECEIVE_BANNER_LIST = 'RECEIVE_BANNER_LIST'

// 逛吃列表action
export const FETCH_FEED_LIST = 'FETCH_FEEDS_LIST';
export const RECEIVE_FEED_LIST = 'RECEIVE_FEEDS_LIST';

// 食物百科action
export const FETCH_CATEGORY_LIST = 'FETCH_CATEGORY_LIST';
export const RECEIVE_CATEGORY_LIST = 'RECEIVE_CATEGORY_LIST';

// 食物列表action
export const FETCH_FOODS_LIST = 'FETCH_FOODS_LIST';
export const RECEIVE_FOODS_LIST = 'RECEIVE_FOODS_LIST';
export const FETCH_SORT_TYPES_LIST = 'FETCH_SORT_TYPES_LIST';
export const RECEIVE_SORT_TYPES_LIST = 'RECEIVE_SORT_TYPES_LIST';
export const SELECT_SORT_TYPE = 'SELECT_SORT_TYPE';
export const RESET_FOODS_LIST_STATE = 'RESET_FOODS_LIST_STATE';
export const CHANGE_SORT_VIEW_STATUS = 'CHANGE_SORT_VIEW_STATUS';
export const ORDER_ASC_OR_DESC = 'ORDER_ASC_OR_DESC';
export const CHANGE_SUBCATEGORY_STATUS = 'CHANGE_SUBCATEGORY_STATUS';
export const SELECT_SUBCATEGORY = 'SELECT_SUBCATEGORY';

// 搜索action
export const FETCH_KEYWORDS_LIST = 'FETCH_KEYWORDS_LIST';
export const RECEIVE_KEYWORDS_LIST = 'RECEIVE_CATEGORY_LIST';